CREATE TABLE AQI2016toPresent (
	cbsa_year VARCHAR (255) PRIMARY KEY NOT NULL,    
	cbsa_name VARCHAR (255) NOT NULL,
    cbsa_code VARCHAR (100) NOT NULL,
	year_y VARCHAR (100) NOT NULL,
    days_with_AQI INTEGER   NOT NULL,
    food_days INTEGER   NOT NULL,
    moderate_days INTEGER   NOT NULL,
    unhealthy_for_sensitivegroups_days INTEGER NOT NULL,
    unhealthy_days INTEGER   NOT NULL,
    very_unhealthy_days INTEGER   NOT NULL,
    hazardous_days INTEGER  NOT NULL,
    max_AQI INTEGER  NOT NULL,
    Ninetieth_percentile_AQI INTEGER NOT NULL,
    median_AQI INTEGER   NOT NULL,
    days_co INTEGER   NOT NULL,
    days_no2 INTEGER   NOT NULL,
    days_ozone INTEGER   NOT NULL,
    days_so2 INTEGER   NOT NULL,
    days_pm25 INTEGER   NOT NULL,
    days_pm10 INTEGER   NOT NULL
);

CREATE TABLE hotness_2016 (
	cbsa_year VARCHAR (255),    	
	cbsa_code VARCHAR (100),
	county_f VARCHAR (100),
	nielsen_hh_rank VARCHAR (100),
	hotness_rank VARCHAR (100),
	hotness_rank_mm VARCHAR (100),
	hotness_rank_yy VARCHAR (100),
	hotness_score VARCHAR (100),
	supply_score VARCHAR (100),
	demand_score VARCHAR (100),
	median_days_on_market VARCHAR (100),
	median_days_on_market_mm VARCHAR (100),
	median_days_on_market_mm_day VARCHAR (100),
	median_days_on_market_yy VARCHAR (100),
	median_days_on_market_yy_day VARCHAR (100),
	median_days_on_market_vs_us VARCHAR (100),
	ldpviews_per_property_mm VARCHAR (100),
	ldpviews_per_property_yy VARCHAR (100),
	ldpviews_per_property_vs_us VARCHAR (100),
	median_listing_price_mm VARCHAR (100),
	median_listing_price_yy VARCHAR (100),
	median_listing_price VARCHAR (100),
	median_listing_price_vs_us VARCHAR (100),
	quality_flag VARCHAR (100),
	year_y VARCHAR (100)
	);